### ISSUE TITLE
Installed in Windows, but nothing happens when opened

### ISSUE THREAD

**Issue by badboyilprimo** [celedev97/asa-server-manager#2]
I installed it in windows but when opened there is nothing appearing

here is the error in the log

`2023-11-22T17:35:22.839+01:00  INFO 22624 --- [main] dev.cele.asa_sm.AsaSmApplication         : Starting AsaSmApplication vv0.0.15 using Java 17.0.9 with PID 22624 (C:\Users\Camaro\AppData\Roaming\ASA Server Manager\asa_sm.jar started by Camaro in C:\Users\Camaro\AppData\Roaming\ASA Server Manager)
2023-11-22T17:35:22.842+01:00  INFO 22624 --- [main] dev.cele.asa_sm.AsaSmApplication         : The following 1 profile is active: "prod"
2023-11-22T17:35:23.369+01:00  INFO 22624 --- [main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=42bfd4bc-9501-3754-9bba-745237904d2c
2023-11-22T17:35:23.574+01:00  INFO 22624 --- [main] dev.cele.asa_sm.AsaSmApplication         : Started AsaSmApplication in 1.25 seconds (process running for 1.671)
2023-11-22T17:35:23.834+01:00  INFO 22624 --- [main] d.cele.asa_sm.services.SettingsService   : LOADING THEME: /dev/cele/asa_sm/themes/nord.theme.json
2023-11-22T17:35:23.836+01:00  INFO 22624 --- [main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-11-22T17:35:23.851+01:00 ERROR 22624 --- [main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-3.1.5.jar!/:3.1.5]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:755) ~[spring-boot-3.1.5.jar!/:3.1.5]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-3.1.5.jar!/:3.1.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-3.1.5.jar!/:3.1.5]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150) ~[spring-boot-3.1.5.jar!/:3.1.5]
	at dev.cele.asa_sm.AsaSmApplication.main(AsaSmApplication.java:46) ~[classes!/:v0.0.15]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[asa_sm.jar:v0.0.15]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[asa_sm.jar:v0.0.15]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[asa_sm.jar:v0.0.15]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[asa_sm.jar:v0.0.15]
Caused by: java.io.FileNotFoundException: \dev\cele\asa_sm\themes\nord.theme.json (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileInputStream.open(Unknown Source) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(Unknown Source) ~[na:na]
	at dev.cele.asa_sm.services.SettingsService.loadTheme(SettingsService.java:62) ~[classes!/:v0.0.15]
	at dev.cele.asa_sm.AsaSmApplication.run(AsaSmApplication.java:54) ~[classes!/:v0.0.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.5.jar!/:3.1.5]
	... 21 common frames omitted

`

**Comment by celedev97** [comment]
Thank you very much for reporting this, the problem should be fixed now with version v0.0.17.
I'll close the bug if there's any problem related to this feel free to re-open it.
